// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/article/article.proto

package article_service // import "rpc/article/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ArticleInfo struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	TopicId              int64    `protobuf:"varint,4,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
	VisibleType          int32    `protobuf:"varint,5,opt,name=visible_type,json=visibleType" json:"visible_type,omitempty"`
	Ctime                int64    `protobuf:"varint,6,opt,name=ctime" json:"ctime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleInfo) Reset()         { *m = ArticleInfo{} }
func (m *ArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleInfo) ProtoMessage()    {}
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{0}
}
func (m *ArticleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleInfo.Unmarshal(m, b)
}
func (m *ArticleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleInfo.Marshal(b, m, deterministic)
}
func (dst *ArticleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleInfo.Merge(dst, src)
}
func (m *ArticleInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleInfo.Size(m)
}
func (m *ArticleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleInfo proto.InternalMessageInfo

func (m *ArticleInfo) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *ArticleInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ArticleInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ArticleInfo) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *ArticleInfo) GetVisibleType() int32 {
	if m != nil {
		return m.VisibleType
	}
	return 0
}

func (m *ArticleInfo) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

type TopicInfo struct {
	TopicId              int64    `protobuf:"varint,1,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicInfo) Reset()         { *m = TopicInfo{} }
func (m *TopicInfo) String() string { return proto.CompactTextString(m) }
func (*TopicInfo) ProtoMessage()    {}
func (*TopicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{1}
}
func (m *TopicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicInfo.Unmarshal(m, b)
}
func (m *TopicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicInfo.Marshal(b, m, deterministic)
}
func (dst *TopicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicInfo.Merge(dst, src)
}
func (m *TopicInfo) XXX_Size() int {
	return xxx_messageInfo_TopicInfo.Size(m)
}
func (m *TopicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TopicInfo proto.InternalMessageInfo

func (m *TopicInfo) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *TopicInfo) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type ArticleRequest struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleRequest) Reset()         { *m = ArticleRequest{} }
func (m *ArticleRequest) String() string { return proto.CompactTextString(m) }
func (*ArticleRequest) ProtoMessage()    {}
func (*ArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{2}
}
func (m *ArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleRequest.Unmarshal(m, b)
}
func (m *ArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleRequest.Marshal(b, m, deterministic)
}
func (dst *ArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleRequest.Merge(dst, src)
}
func (m *ArticleRequest) XXX_Size() int {
	return xxx_messageInfo_ArticleRequest.Size(m)
}
func (m *ArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleRequest proto.InternalMessageInfo

func (m *ArticleRequest) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type ArticleResponse struct {
	ArticleInfo          *ArticleInfo `protobuf:"bytes,1,opt,name=article_info,json=articleInfo" json:"article_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ArticleResponse) Reset()         { *m = ArticleResponse{} }
func (m *ArticleResponse) String() string { return proto.CompactTextString(m) }
func (*ArticleResponse) ProtoMessage()    {}
func (*ArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{3}
}
func (m *ArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleResponse.Unmarshal(m, b)
}
func (m *ArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleResponse.Marshal(b, m, deterministic)
}
func (dst *ArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleResponse.Merge(dst, src)
}
func (m *ArticleResponse) XXX_Size() int {
	return xxx_messageInfo_ArticleResponse.Size(m)
}
func (m *ArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleResponse proto.InternalMessageInfo

func (m *ArticleResponse) GetArticleInfo() *ArticleInfo {
	if m != nil {
		return m.ArticleInfo
	}
	return nil
}

type ArticleBatchRequest struct {
	ArticleIds           []int64  `protobuf:"varint,1,rep,packed,name=article_ids,json=articleIds" json:"article_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleBatchRequest) Reset()         { *m = ArticleBatchRequest{} }
func (m *ArticleBatchRequest) String() string { return proto.CompactTextString(m) }
func (*ArticleBatchRequest) ProtoMessage()    {}
func (*ArticleBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{4}
}
func (m *ArticleBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleBatchRequest.Unmarshal(m, b)
}
func (m *ArticleBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleBatchRequest.Marshal(b, m, deterministic)
}
func (dst *ArticleBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleBatchRequest.Merge(dst, src)
}
func (m *ArticleBatchRequest) XXX_Size() int {
	return xxx_messageInfo_ArticleBatchRequest.Size(m)
}
func (m *ArticleBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleBatchRequest proto.InternalMessageInfo

func (m *ArticleBatchRequest) GetArticleIds() []int64 {
	if m != nil {
		return m.ArticleIds
	}
	return nil
}

type ArticleBatchResponse struct {
	ArticleInfos         map[int64]*ArticleInfo `protobuf:"bytes,1,rep,name=article_infos,json=articleInfos" json:"article_infos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ArticleBatchResponse) Reset()         { *m = ArticleBatchResponse{} }
func (m *ArticleBatchResponse) String() string { return proto.CompactTextString(m) }
func (*ArticleBatchResponse) ProtoMessage()    {}
func (*ArticleBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{5}
}
func (m *ArticleBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleBatchResponse.Unmarshal(m, b)
}
func (m *ArticleBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleBatchResponse.Marshal(b, m, deterministic)
}
func (dst *ArticleBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleBatchResponse.Merge(dst, src)
}
func (m *ArticleBatchResponse) XXX_Size() int {
	return xxx_messageInfo_ArticleBatchResponse.Size(m)
}
func (m *ArticleBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleBatchResponse proto.InternalMessageInfo

func (m *ArticleBatchResponse) GetArticleInfos() map[int64]*ArticleInfo {
	if m != nil {
		return m.ArticleInfos
	}
	return nil
}

type TopicRequest struct {
	TopicId              int64    `protobuf:"varint,1,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicRequest) Reset()         { *m = TopicRequest{} }
func (m *TopicRequest) String() string { return proto.CompactTextString(m) }
func (*TopicRequest) ProtoMessage()    {}
func (*TopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{6}
}
func (m *TopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicRequest.Unmarshal(m, b)
}
func (m *TopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicRequest.Marshal(b, m, deterministic)
}
func (dst *TopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicRequest.Merge(dst, src)
}
func (m *TopicRequest) XXX_Size() int {
	return xxx_messageInfo_TopicRequest.Size(m)
}
func (m *TopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopicRequest proto.InternalMessageInfo

func (m *TopicRequest) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

type TopicBatchRequest struct {
	TopicIds             []int64  `protobuf:"varint,1,rep,packed,name=topic_ids,json=topicIds" json:"topic_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicBatchRequest) Reset()         { *m = TopicBatchRequest{} }
func (m *TopicBatchRequest) String() string { return proto.CompactTextString(m) }
func (*TopicBatchRequest) ProtoMessage()    {}
func (*TopicBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{7}
}
func (m *TopicBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicBatchRequest.Unmarshal(m, b)
}
func (m *TopicBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicBatchRequest.Marshal(b, m, deterministic)
}
func (dst *TopicBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicBatchRequest.Merge(dst, src)
}
func (m *TopicBatchRequest) XXX_Size() int {
	return xxx_messageInfo_TopicBatchRequest.Size(m)
}
func (m *TopicBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopicBatchRequest proto.InternalMessageInfo

func (m *TopicBatchRequest) GetTopicIds() []int64 {
	if m != nil {
		return m.TopicIds
	}
	return nil
}

type TopicResponse struct {
	TopicInfo            *TopicInfo `protobuf:"bytes,1,opt,name=topic_info,json=topicInfo" json:"topic_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TopicResponse) Reset()         { *m = TopicResponse{} }
func (m *TopicResponse) String() string { return proto.CompactTextString(m) }
func (*TopicResponse) ProtoMessage()    {}
func (*TopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{8}
}
func (m *TopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicResponse.Unmarshal(m, b)
}
func (m *TopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicResponse.Marshal(b, m, deterministic)
}
func (dst *TopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicResponse.Merge(dst, src)
}
func (m *TopicResponse) XXX_Size() int {
	return xxx_messageInfo_TopicResponse.Size(m)
}
func (m *TopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopicResponse proto.InternalMessageInfo

func (m *TopicResponse) GetTopicInfo() *TopicInfo {
	if m != nil {
		return m.TopicInfo
	}
	return nil
}

type TopicBatchResponse struct {
	TopicInfos           map[int64]*TopicInfo `protobuf:"bytes,1,rep,name=topic_infos,json=topicInfos" json:"topic_infos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TopicBatchResponse) Reset()         { *m = TopicBatchResponse{} }
func (m *TopicBatchResponse) String() string { return proto.CompactTextString(m) }
func (*TopicBatchResponse) ProtoMessage()    {}
func (*TopicBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{9}
}
func (m *TopicBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicBatchResponse.Unmarshal(m, b)
}
func (m *TopicBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicBatchResponse.Marshal(b, m, deterministic)
}
func (dst *TopicBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicBatchResponse.Merge(dst, src)
}
func (m *TopicBatchResponse) XXX_Size() int {
	return xxx_messageInfo_TopicBatchResponse.Size(m)
}
func (m *TopicBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopicBatchResponse proto.InternalMessageInfo

func (m *TopicBatchResponse) GetTopicInfos() map[int64]*TopicInfo {
	if m != nil {
		return m.TopicInfos
	}
	return nil
}

type PublishArticleRequest struct {
	ArticleInfo          *ArticleInfo `protobuf:"bytes,1,opt,name=article_info,json=articleInfo" json:"article_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PublishArticleRequest) Reset()         { *m = PublishArticleRequest{} }
func (m *PublishArticleRequest) String() string { return proto.CompactTextString(m) }
func (*PublishArticleRequest) ProtoMessage()    {}
func (*PublishArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{10}
}
func (m *PublishArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishArticleRequest.Unmarshal(m, b)
}
func (m *PublishArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishArticleRequest.Marshal(b, m, deterministic)
}
func (dst *PublishArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishArticleRequest.Merge(dst, src)
}
func (m *PublishArticleRequest) XXX_Size() int {
	return xxx_messageInfo_PublishArticleRequest.Size(m)
}
func (m *PublishArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishArticleRequest proto.InternalMessageInfo

func (m *PublishArticleRequest) GetArticleInfo() *ArticleInfo {
	if m != nil {
		return m.ArticleInfo
	}
	return nil
}

type VisibleTypeRequest struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	VisibleType          int32    `protobuf:"varint,2,opt,name=visible_type,json=visibleType" json:"visible_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisibleTypeRequest) Reset()         { *m = VisibleTypeRequest{} }
func (m *VisibleTypeRequest) String() string { return proto.CompactTextString(m) }
func (*VisibleTypeRequest) ProtoMessage()    {}
func (*VisibleTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{11}
}
func (m *VisibleTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisibleTypeRequest.Unmarshal(m, b)
}
func (m *VisibleTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisibleTypeRequest.Marshal(b, m, deterministic)
}
func (dst *VisibleTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisibleTypeRequest.Merge(dst, src)
}
func (m *VisibleTypeRequest) XXX_Size() int {
	return xxx_messageInfo_VisibleTypeRequest.Size(m)
}
func (m *VisibleTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VisibleTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VisibleTypeRequest proto.InternalMessageInfo

func (m *VisibleTypeRequest) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *VisibleTypeRequest) GetVisibleType() int32 {
	if m != nil {
		return m.VisibleType
	}
	return 0
}

type PushInBoxRequest struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushInBoxRequest) Reset()         { *m = PushInBoxRequest{} }
func (m *PushInBoxRequest) String() string { return proto.CompactTextString(m) }
func (*PushInBoxRequest) ProtoMessage()    {}
func (*PushInBoxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{12}
}
func (m *PushInBoxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushInBoxRequest.Unmarshal(m, b)
}
func (m *PushInBoxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushInBoxRequest.Marshal(b, m, deterministic)
}
func (dst *PushInBoxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushInBoxRequest.Merge(dst, src)
}
func (m *PushInBoxRequest) XXX_Size() int {
	return xxx_messageInfo_PushInBoxRequest.Size(m)
}
func (m *PushInBoxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushInBoxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushInBoxRequest proto.InternalMessageInfo

func (m *PushInBoxRequest) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *PushInBoxRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetInBoxRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Cursor               int64    `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInBoxRequest) Reset()         { *m = GetInBoxRequest{} }
func (m *GetInBoxRequest) String() string { return proto.CompactTextString(m) }
func (*GetInBoxRequest) ProtoMessage()    {}
func (*GetInBoxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{13}
}
func (m *GetInBoxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInBoxRequest.Unmarshal(m, b)
}
func (m *GetInBoxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInBoxRequest.Marshal(b, m, deterministic)
}
func (dst *GetInBoxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInBoxRequest.Merge(dst, src)
}
func (m *GetInBoxRequest) XXX_Size() int {
	return xxx_messageInfo_GetInBoxRequest.Size(m)
}
func (m *GetInBoxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInBoxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInBoxRequest proto.InternalMessageInfo

func (m *GetInBoxRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetInBoxRequest) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *GetInBoxRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetInBoxResponse struct {
	ArticleIds           []int64  `protobuf:"varint,1,rep,packed,name=article_ids,json=articleIds" json:"article_ids,omitempty"`
	NextCursor           int64    `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor" json:"next_cursor,omitempty"`
	HasMore              bool     `protobuf:"varint,3,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInBoxResponse) Reset()         { *m = GetInBoxResponse{} }
func (m *GetInBoxResponse) String() string { return proto.CompactTextString(m) }
func (*GetInBoxResponse) ProtoMessage()    {}
func (*GetInBoxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{14}
}
func (m *GetInBoxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInBoxResponse.Unmarshal(m, b)
}
func (m *GetInBoxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInBoxResponse.Marshal(b, m, deterministic)
}
func (dst *GetInBoxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInBoxResponse.Merge(dst, src)
}
func (m *GetInBoxResponse) XXX_Size() int {
	return xxx_messageInfo_GetInBoxResponse.Size(m)
}
func (m *GetInBoxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInBoxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInBoxResponse proto.InternalMessageInfo

func (m *GetInBoxResponse) GetArticleIds() []int64 {
	if m != nil {
		return m.ArticleIds
	}
	return nil
}

func (m *GetInBoxResponse) GetNextCursor() int64 {
	if m != nil {
		return m.NextCursor
	}
	return 0
}

func (m *GetInBoxResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_4695e5dc63639bda, []int{15}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ArticleInfo)(nil), "article.ArticleInfo")
	proto.RegisterType((*TopicInfo)(nil), "article.TopicInfo")
	proto.RegisterType((*ArticleRequest)(nil), "article.ArticleRequest")
	proto.RegisterType((*ArticleResponse)(nil), "article.ArticleResponse")
	proto.RegisterType((*ArticleBatchRequest)(nil), "article.ArticleBatchRequest")
	proto.RegisterType((*ArticleBatchResponse)(nil), "article.ArticleBatchResponse")
	proto.RegisterMapType((map[int64]*ArticleInfo)(nil), "article.ArticleBatchResponse.ArticleInfosEntry")
	proto.RegisterType((*TopicRequest)(nil), "article.TopicRequest")
	proto.RegisterType((*TopicBatchRequest)(nil), "article.TopicBatchRequest")
	proto.RegisterType((*TopicResponse)(nil), "article.TopicResponse")
	proto.RegisterType((*TopicBatchResponse)(nil), "article.TopicBatchResponse")
	proto.RegisterMapType((map[int64]*TopicInfo)(nil), "article.TopicBatchResponse.TopicInfosEntry")
	proto.RegisterType((*PublishArticleRequest)(nil), "article.PublishArticleRequest")
	proto.RegisterType((*VisibleTypeRequest)(nil), "article.VisibleTypeRequest")
	proto.RegisterType((*PushInBoxRequest)(nil), "article.PushInBoxRequest")
	proto.RegisterType((*GetInBoxRequest)(nil), "article.GetInBoxRequest")
	proto.RegisterType((*GetInBoxResponse)(nil), "article.GetInBoxResponse")
	proto.RegisterType((*EmptyResponse)(nil), "article.EmptyResponse")
}

func init() {
	proto.RegisterFile("proto/article/article.proto", fileDescriptor_article_4695e5dc63639bda)
}

var fileDescriptor_article_4695e5dc63639bda = []byte{
	// 760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5d, 0x4f, 0xdb, 0x4a,
	0x10, 0x95, 0x09, 0x21, 0xf1, 0x38, 0x21, 0xb0, 0x17, 0xb8, 0x4e, 0xb8, 0x70, 0x53, 0x3f, 0xa5,
	0xad, 0x04, 0x2d, 0x95, 0xfa, 0x29, 0x95, 0x36, 0x14, 0x41, 0xaa, 0x16, 0x51, 0x43, 0x79, 0xe8,
	0x4b, 0xe4, 0x38, 0x93, 0xc6, 0x6a, 0x62, 0xbb, 0xde, 0x4d, 0x44, 0xfe, 0x53, 0x5f, 0xfb, 0x0b,
	0xfa, 0xb7, 0xfa, 0x50, 0x79, 0xbd, 0xeb, 0x8f, 0x7c, 0x00, 0xea, 0x53, 0xbc, 0xb3, 0x7b, 0xce,
	0x9c, 0x3d, 0x33, 0xb3, 0x0a, 0x6c, 0xfb, 0x81, 0xc7, 0xbc, 0x7d, 0x2b, 0x60, 0x8e, 0x3d, 0x40,
	0xf9, 0xbb, 0xc7, 0xa3, 0xa4, 0x20, 0x96, 0xc6, 0x0f, 0x05, 0xb4, 0xb7, 0xd1, 0x77, 0xcb, 0xed,
	0x79, 0x64, 0x07, 0x40, 0x6c, 0xb5, 0x9d, 0xae, 0xae, 0xd4, 0x95, 0x46, 0xce, 0x54, 0x45, 0xa4,
	0xd5, 0x25, 0x6b, 0x90, 0x1b, 0x39, 0x5d, 0x7d, 0x89, 0xc7, 0xc3, 0x4f, 0xa2, 0x43, 0xc1, 0xf6,
	0x5c, 0x86, 0x2e, 0xd3, 0x73, 0x75, 0xa5, 0xa1, 0x9a, 0x72, 0x49, 0xaa, 0x50, 0x64, 0x9e, 0xef,
	0xd8, 0x21, 0xd1, 0x32, 0x07, 0x14, 0xf8, 0xba, 0xd5, 0x25, 0xf7, 0xa0, 0x34, 0x76, 0xa8, 0xd3,
	0x19, 0x60, 0x9b, 0x4d, 0x7c, 0xd4, 0xf3, 0x75, 0xa5, 0x91, 0x37, 0x35, 0x11, 0xbb, 0x9c, 0xf8,
	0x48, 0x36, 0x20, 0x6f, 0x33, 0x67, 0x88, 0xfa, 0x0a, 0x87, 0x46, 0x0b, 0xe3, 0x18, 0xd4, 0x4b,
	0xce, 0x11, 0x6a, 0x4d, 0x27, 0x50, 0xb2, 0x09, 0x76, 0x00, 0xa2, 0x2d, 0xd7, 0x1a, 0x22, 0x97,
	0xab, 0x9a, 0x2a, 0x8f, 0x9c, 0x59, 0x43, 0x34, 0xf6, 0x61, 0x55, 0x5c, 0xda, 0xc4, 0xef, 0x23,
	0xa4, 0xec, 0x96, 0x7b, 0x1b, 0xef, 0xa1, 0x12, 0x03, 0xa8, 0xef, 0xb9, 0x14, 0xc9, 0x33, 0x28,
	0xc5, 0x08, 0xb7, 0xe7, 0x71, 0x8c, 0x76, 0xb0, 0xb1, 0x27, 0x8d, 0x4e, 0xb9, 0x6a, 0x6a, 0x56,
	0xb2, 0x30, 0x9e, 0xc2, 0x3f, 0x62, 0xaf, 0x69, 0x31, 0xbb, 0x2f, 0x15, 0xfc, 0x0f, 0x5a, 0xa2,
	0x80, 0xea, 0x4a, 0x3d, 0xd7, 0xc8, 0x99, 0x10, 0x4b, 0xa0, 0xc6, 0x2f, 0x05, 0x36, 0xb2, 0x40,
	0xa1, 0xe4, 0x12, 0xca, 0x69, 0x25, 0x11, 0x56, 0x3b, 0xd8, 0x9f, 0x96, 0x92, 0x41, 0xa5, 0xf5,
	0xd1, 0x63, 0x97, 0x05, 0x13, 0xb3, 0x94, 0x52, 0x49, 0x6b, 0x9f, 0x61, 0x7d, 0xe6, 0x48, 0x58,
	0xff, 0x6f, 0x38, 0x11, 0xfe, 0x84, 0x9f, 0xe4, 0x01, 0xe4, 0xc7, 0xd6, 0x60, 0x14, 0x99, 0xbc,
	0xe8, 0xfe, 0xd1, 0x91, 0x97, 0x4b, 0xcf, 0x15, 0xe3, 0x3e, 0x94, 0x78, 0x05, 0xe5, 0xb5, 0x17,
	0x17, 0xd1, 0x78, 0x04, 0xeb, 0xfc, 0x68, 0xc6, 0xa6, 0x6d, 0x50, 0xe5, 0x79, 0x69, 0x52, 0x51,
	0x00, 0xa8, 0xd1, 0x84, 0xb2, 0x20, 0x17, 0xd6, 0x3c, 0x96, 0x7d, 0x90, 0x2a, 0x11, 0x89, 0x25,
	0xc6, 0xad, 0x24, 0x7a, 0x83, 0x97, 0xe7, 0xa7, 0x02, 0x24, 0x9d, 0x56, 0x30, 0x7d, 0x00, 0x2d,
	0x61, 0x92, 0x16, 0x3f, 0xcc, 0x52, 0x65, 0x0d, 0x8e, 0xd9, 0x85, 0xbd, 0x10, 0xe7, 0xa0, 0xb5,
	0x4f, 0x50, 0x99, 0xda, 0x9e, 0x63, 0x6d, 0x23, 0x6b, 0xed, 0x3c, 0xdd, 0x29, 0x63, 0xcf, 0x61,
	0xf3, 0x7c, 0xd4, 0x19, 0x38, 0xb4, 0x3f, 0xd5, 0xda, 0x7f, 0xdd, 0xa8, 0x57, 0x40, 0xae, 0x92,
	0x89, 0xbc, 0xdb, 0xa4, 0xcc, 0x8c, 0xf6, 0xd2, 0xcc, 0x68, 0x1b, 0x47, 0xb0, 0x76, 0x3e, 0xa2,
	0xfd, 0x96, 0xdb, 0xf4, 0xae, 0xef, 0xc8, 0x3a, 0xf3, 0xee, 0x18, 0x17, 0x50, 0x39, 0x41, 0x96,
	0xe1, 0x10, 0x87, 0x94, 0xe4, 0x71, 0xda, 0x82, 0x15, 0x7b, 0x14, 0x50, 0x2f, 0x10, 0x48, 0xb1,
	0x0a, 0xe3, 0x5e, 0xaf, 0x47, 0x31, 0x7a, 0xb3, 0x72, 0xa6, 0x58, 0x19, 0x1e, 0xac, 0x25, 0xa4,
	0xa2, 0xf0, 0xb7, 0xcd, 0x65, 0x78, 0xc0, 0xc5, 0x6b, 0xd6, 0xce, 0x64, 0x82, 0x30, 0x74, 0x14,
	0x65, 0xab, 0x42, 0xb1, 0x6f, 0xd1, 0xf6, 0xd0, 0x0b, 0x90, 0xe7, 0x2b, 0x9a, 0x85, 0xbe, 0x45,
	0x3f, 0x7a, 0x01, 0x1a, 0x15, 0x28, 0x1f, 0x0f, 0x7d, 0x36, 0x91, 0xd9, 0x0e, 0x7e, 0x2f, 0x43,
	0x59, 0x14, 0xe4, 0x02, 0x83, 0x31, 0x06, 0xe4, 0x10, 0xe0, 0x04, 0x99, 0x88, 0x91, 0x7f, 0xa7,
	0xcb, 0x26, 0x2e, 0x5f, 0xd3, 0x67, 0x37, 0xc4, 0x05, 0xce, 0xb8, 0x53, 0xbc, 0x37, 0x25, 0xcb,
	0x7f, 0x0b, 0x9e, 0x86, 0x88, 0x6a, 0xe7, 0xc6, 0x87, 0x83, 0xbc, 0x80, 0xe2, 0x09, 0x32, 0xde,
	0x83, 0x64, 0x33, 0xdb, 0x93, 0x92, 0x61, 0x6b, 0x3a, 0x2c, 0xa0, 0xa7, 0x50, 0x96, 0x52, 0x22,
	0x7c, 0x6d, 0xee, 0x00, 0x45, 0x24, 0xdb, 0x37, 0x0c, 0x17, 0x39, 0x85, 0xf5, 0xa3, 0xbe, 0xe5,
	0x7e, 0xc5, 0x54, 0x87, 0x92, 0x04, 0x31, 0xdb, 0xb7, 0x29, 0x4d, 0x19, 0xc7, 0xc9, 0x29, 0xac,
	0x66, 0xe7, 0x86, 0xec, 0xc6, 0x27, 0xe7, 0x0e, 0xd4, 0x42, 0xa6, 0x37, 0x50, 0x7e, 0x87, 0x03,
	0x64, 0x78, 0x6b, 0xb1, 0x16, 0x31, 0xbc, 0x06, 0x35, 0x9e, 0x0c, 0x52, 0x4d, 0xc9, 0xc8, 0x4e,
	0xcb, 0x42, 0xfc, 0x21, 0x2f, 0x4d, 0x04, 0x4f, 0x1a, 0x62, 0x6a, 0x4e, 0x6a, 0xd5, 0x39, 0x3b,
	0x11, 0x41, 0xb3, 0xfe, 0x65, 0x37, 0xf0, 0xed, 0xf8, 0x4f, 0x83, 0xdf, 0x79, 0x25, 0x7b, 0x9f,
	0x62, 0x30, 0x76, 0x6c, 0xec, 0xac, 0xf0, 0x3f, 0x10, 0x4f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x27, 0x4e, 0x90, 0x5b, 0x5f, 0x08, 0x00, 0x00,
}
